package auth

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// CredFileName is the name of the credential file written to project directories.
const CredFileName = ".claude-quick-auth"

// WriteCredentialFile writes the resolved credentials to a file in the project directory.
// The file is written with restricted permissions (0600) and can be sourced by shells.
func WriteCredentialFile(projectPath string, creds map[string]string) error {
	if len(creds) == 0 {
		return nil
	}

	filePath := filepath.Join(projectPath, CredFileName)

	var buf strings.Builder
	buf.WriteString("# Generated by claude-quick - DO NOT COMMIT\n")
	buf.WriteString("# This file contains authentication credentials\n")
	buf.WriteString("# Source this file: source .claude-quick-auth\n\n")

	for name, value := range creds {
		// Escape single quotes in value by ending the quote, adding escaped quote, and starting new quote
		escaped := strings.ReplaceAll(value, "'", "'\"'\"'")
		buf.WriteString(fmt.Sprintf("export %s='%s'\n", name, escaped))
	}

	// Write with restricted permissions (600 = owner read/write only)
	if err := os.WriteFile(filePath, []byte(buf.String()), 0600); err != nil {
		return fmt.Errorf("failed to write credential file: %w", err)
	}

	return nil
}

// CleanupCredentialFile removes the credential file from a project directory.
func CleanupCredentialFile(projectPath string) error {
	filePath := filepath.Join(projectPath, CredFileName)
	if err := os.Remove(filePath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove credential file: %w", err)
	}
	return nil
}

// CredentialFilePath returns the path to the credential file for a project.
func CredentialFilePath(projectPath string) string {
	return filepath.Join(projectPath, CredFileName)
}
